name: Quality Report

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-report:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate quality report with test results
        run: |
          # Add debugging information
          echo "Current directory: $(pwd)"
          echo "Content of scripts/quality directory:"
          ls -la scripts/quality/
          echo "Content of scripts/quality/output directory (before running reports):"
          ls -la scripts/quality/output/ || echo "Output directory doesn't exist yet"
          
          # Create output directory if it doesn't exist
          mkdir -p scripts/quality/output
          
          # Make the new GitHub-specific script executable
          chmod +x scripts/quality/github-build.js
          
          # Run the dedicated GitHub build script (much simpler than the complex script chain)
          echo "Running GitHub-specific build script..."
          node scripts/quality/github-build.js

      - name: Create report directory
        run: |
          echo "Creating quality-report directory"
          mkdir -p quality-report
          
          # Copy all files from output to quality-report
          echo "Copying output files to quality-report"
          if [ -d "scripts/quality/output" ]; then
            cp -r scripts/quality/output/* quality-report/ || echo "No files to copy from output directory"
          fi
          
          # Copy any standalone files
          if [ -f "scripts/quality/quality-tag-checkpoint.ndjson" ]; then
            cp scripts/quality/quality-tag-checkpoint.ndjson quality-report/ || echo "Failed to copy checkpoint file"
          fi
          
          # List contents of quality-report directory
          echo "Contents of quality-report directory:"
          ls -la quality-report/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'quality-report'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output quality report URL
        run: |
          echo "::notice title=Quality Report::Quality report is available at ${{ steps.deployment.outputs.page_url }}" 