name: Sanity MCP Server Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run nightly at midnight UTC

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm run typecheck
      - run: npm run test:unit

  critical-integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm run test:integration:critical
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
    
  standard-integration-tests:
    runs-on: ubuntu-latest
    needs: critical-integration-tests
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm run test:integration:standard
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
  
  # Integration tests configuration:
  # - Critical tests run in CI first for all events
  # - Standard tests run in CI after critical tests pass for pull requests and pushes to main
  # - Extended tests only run locally for specific feature testing
